name: Check PR required labels and comment

on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]

jobs:
  check-pr-label-and-comment:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: freshactions/pr-label-check-and-comment-action
          ref: master
          path: ./.github/actions/pr-label-check-and-comment-action
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - uses: ./.github/actions/pr-label-check-and-comment-action
        with:
          required_labels: 'ğŸ† feature, ğŸ† user-story, ğŸ‹ğŸ»â€â™‚ï¸ enhancement, ğŸ‹ğŸ»â€â™‚ï¸ task, ğŸ•· fix, ğŸ•· bug, ğŸ” security-bug, ğŸ” security, ğŸ“ chore, ğŸ“ docs'
          GITHUB_TOKEN: '${{secrets.GITHUB_TOKEN}}'
